### ISSUE TITLE
Took very long time on the first run

### ISSUE THREAD

**Issue by borekb** [askgitdev/askgit#46] opened 2020-08-30 08:10 UTC
Is it expected that the basic command from README is so heavy? I initially thought that there's something wrong with my invocation, I did this:

```
docker run --rm -v `pwd`:/repo:ro augmentable/askgit "SELECT * FROM commits"
```

Then my computer just seemed to be stuck. I was seeing resource usage like this for over a minute:

<img width="1152" alt="Screenshot 2020-08-30 at 10 02 57" src="https://user-images.githubusercontent.com/101152/91654422-c6dd0400-eaa8-11ea-911f-8a133a5a9966.png">

Then it eventually finished after about 2.5 minutes but I was seriously worried that I'm doing something wrong, e.g., not escaping the SQL query correctly.

What does it do on the first run? Is it building some sort of database behind the scenes? Would even "simpler" queries like `SELECT count(*) FROM commits` take similarly long?

**Comment by patrickdevivo** [comment] 2020-08-30 16:18
Hi @borekb, thanks for opening this issue up. That's definitely a long execution time and high resource consumption. For clarity, there's no pre-loading or pre-caching that currently occurs, a query like `SELECT * FROM commits` essentially maps to a `git log ...` call.

I think I understand what's possibly causing this bottleneck, in your case since I see you're using Docker. There are currently two methods of accessing git data: 1) shelling out to the `git` CLI and 2) using [`go-git`](https://github.com/go-git/go-git). The `git` shell method was implemented because there were performance issues using `go-git`, and I figured most users would have `git` installed on their systems anyway. However, in the docker container it's possible git isn't available, so it's using the slower `go-git` method.

Let me dig a little deeper. Is the repo you are running the queries on particular large? In terms of commit count?

**Comment by borekb** [comment] 2020-08-30 16:23
Thanks for looking into it.

> Is the repo you are running the queries on particular large? In terms of commit count?

Nope:

```
$ docker run --rm -v `pwd`:/repo:ro augmentable/askgit "SELECT count(*) FROM commits"
+----------+
| COUNT(*) |
+----------+
|     3127 |
+----------+
```

**Comment by patrickdevivo** [comment] 2020-08-30 16:37
@borekb please try using the latest docker image now, see if that helps

**Comment by borekb** [comment] 2020-08-30 17:12
Unfortunately, it's now a lot slower, for example, that `count(*)` now takes over 22 seconds (was below 5 seconds previously).

To make sure I'm running the correct image version, I did this:

```
$ docker run --rm -v `pwd`:/repo:ro docker.io/augmentable/askgit@sha256:ba3c27c17e07a945bc8ac2eb8627975b7d7eb382e19029facb0b0632a1823c2f "SELECT count(*) FROM commits"
```

**Comment by patrickdevivo** [comment] 2020-09-02 02:32
Hi @borekb I'm sorry about that, that is bizarre and I was able to reproduce on a local checkout of a ~large repo (the kubernetes source code). It appears there's a performance degradation using docker vs a native binary, which I suppose is expected to some degree, but is surprisingly significant (from my ad-hoc testing). In your case, a 3k commit repo and 20+ seconds of output does seem long as well. I will continue to investigate and see what turns up, query performance is something I certainly hope to improve in general, especially for simple queries such as these.

**Comment by patrickdevivo** [comment] 2021-08-12 14:05
Closing due to staleness, the code has changed quite a bit in recent weeks - happy to reopen if this issue is still persisting on a recent version

**Closed by patrickdevivo** 2021-08-12 14:05 UTC
